In [1]:
# mnist dataset
# has handwritten digits form 0 to 9 about 70 thousand images are provided alogn with the labels, 
# 60 thousand for training and 10 thousand for testin all the images have same size of 28 X 28.

# Importing necessar libraries.

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from tensorflow import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense
print('Libraries imported succesfully')

Libraries imported succesfully


# load the mnist data set

In [3]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(60000, 28, 28) (60000,)
(10000, 28, 28) (10000,)


# preprocess the images 

In [4]:

# as ANN can accept only 10 data, reshape images  from 2d to 1d
Xm_train = x_train.reshape((60000, 784))
Xm_test = x_test.reshape((10000,784))
print(Xm_train.shape, Xm_test.shape)

#normalizing all the images to 0 to 1.
Xm_train=Xm_train/255
Xm_test=Xm_test/255

(60000, 784) (10000, 784)


# Encode the label 

In [5]:
from keras.utils import to_categorical
Ymtrain = to_categorical(y_train)
ymtest = to_categorical(y_test)

In [6]:
print(y_train[0:3])
print(Ymtrain[0:3])

[5 0 4]
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


# now build neural network architecture

In [7]:
ANN_model = Sequential()
ANN_model.add(Dense(input_shape=[784],units=256,activation='relu'))
ANN_model.add(Dense(units=10, activation='sigmoid'))

ANN_model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
ANN_model.summary()

C:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 256)                 │         200,960 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 10)                  │           2,570 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 203,530 (795.04 KB)

 Trainable params: 203,530 (795.04 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
ANN_model.fit(Xm_train,Ymtrain, epochs = 5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 24s 11ms/step - accuracy: 0.8899 - loss: 0.3774
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 19s 10ms/step - accuracy: 0.9714 - loss: 0.0969
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 19s 10ms/step - accuracy: 0.9807 - loss: 0.0622
Epoch 4/5
1527/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.9888 - loss: 0.0372

# Single imapre prediction. also called as sample test

In [ ]:
plt.imshow(x_test[4000],cmap = 'Greens')
plt.show()
R = ANN_model.predict(Xm_test[4000:4001])
print(f"Probabiliteis {R}")
print(f"The digit is: {np.argmax(R)}")

# Model Save

In [ ]:
ANN_model.save("handwritten_digit_ann_model_best1.h5") #saving with hdf5 format
ANN_model.save("hadnwritten_digit_ann_model_best1.keras") # keras 